version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/deploy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:59"
      timezone: "Europe/Oslo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:59"
      timezone: "Europe/Oslo"

  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:59"
      timezone: "Europe/Oslo"
