# nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smia-ogc-api
  tags:
    - public
spec:
  type: service
  lifecycle: production
  owner: smia
  system: nibas
  providesApis:
    - smia-ogc-api
  consumesApis:
    - api:default/matrikkel-api
  dependsOn:
    - resource:default/inndelinger-database
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: smia-ogc-api
  tags:
    - public
spec:
  type: openapi
  lifecycle: production
  owner: smia
  system: nibas
  definition: |
    openapi: "3.0.0"
    info:
        title: smia-ogc-api API
    paths:
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inndelinger-database
  tags:
    - internal
spec:
  type: database
  owner: smia
  system: nibas
