name: Build, push and deploy to ArgoCD

on:
  push:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: kartverket/smia-ogc-api
  SMIA_APPS_VERSION_FILE: env/atkv3-dev/smia-tjenester-main/smia-ogc-api-version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read

    outputs:
      version: ${{ steps.set_output.outputs.version }}
      image_url: ${{ steps.set_output.outputs.image_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ github.token }}

      - name: Login to Github Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }} , ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Set output with build values
        id: set_output
        run: |
          echo "version=${{ steps.tag_version.outputs.new_tag }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          echo "image_url=${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos security scan
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@599d3fe4af8bae19fbfda831662e90ee1c406ec2 # v0.6.3
        with:
          allow_severity_level: medium
          image_url: ${{ needs.build.outputs.image_url }}

  deploy-argo:
    permissions:
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    concurrency: smia-deploy
    steps:
      - name: Octo STS
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: kartverket/smia-apps
          identity: restapi

      - name: Checkout the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: kartverket/smia-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Update smia-apps and push
        run: |
          git config --global user.email "smia@kartverket.no"
          git config --global user.name "SMIA CI"
          git pull --ff-only origin main

          IMAGEURL="${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.version }}"

          echo "### Deploying \"$IMAGEURL\"" >> $GITHUB_STEP_SUMMARY
          echo 'Deploy to dev? true' >> $GITHUB_STEP_SUMMARY
          
          # Write the new version to the dev environment file
          echo "\"$IMAGEURL\"" > "$SMIA_APPS_VERSION_FILE"
          
          git add "$SMIA_APPS_VERSION_FILE"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Releaser smia-ogc-api:${{ needs.build.outputs.version }}"
            git push origin HEAD:main
          fi